name: Deploy Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          
      - name: Connect to VPN
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" > client.ovpn
          sudo openvpn --config client.ovpn --daemon
          sleep 10  # Aspetta che la connessione venga stabilita

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no user@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.WEBAPP_PATH }}
            git pull origin main
            docker compose restart
          EOF
